search_app/urls.py
from django.conf.urls import url
from views import index, search_results, index_url, indexed_urls

app_name = 'search_app'
urlpatterns = [
    url(r'^search_results/(?P<query>.*)$', search_results, name='search_results'),
    url(r'index_url', index_url, name='index_url'),
    url(r'indexed_urls', indexed_urls, name='indexed_urls'),
    url(r'.*', index, name='index'),
]

search_engine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from search_app import urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(urls))
]

search_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class CrawledPage(models.Model):
    url = models.URLField(null=False)

search_app/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label='query', min_length=1, required=True)


class IndexUrlForm(forms.Form):
    url_to_index = forms.CharField(label='url to index', min_length=5,required=False)
    file = forms.FileField(required=False, allow_empty_file=False,)

search_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from forms import SearchForm, IndexUrlForm
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from logic.indexer import ShelveIndexer
from logic.searcher import Searcher
from logic.metadata import INDICES_DIR, INDEX_WIKI, CRAWLED_USER_PAGES, INDEX_WIKI_MINI, H
from logic.crawler import crawl_page
import multiprocessing.pool
import time

searcher = Searcher(H, ShelveIndexer)


@require_http_methods(['GET', 'POST'])
def index(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            return HttpResponseRedirect(reverse('search_app:search_results', args=(query,)))
        return render(request, 'search_app/index.html', {'form': form})
    elif request.method == 'GET':
        form = SearchForm()
        return render(request, 'search_app/index.html', {'form': form})


@require_http_methods(['GET'])
def search_results(request, query):
    # print 'search_results!'
    # query_words = query_terms(query)
    # id_pos = searcher.find_document(query_words)
    # print to_query_terms(query)
    begin_search_time = time.time()
    ids = searcher.find(query)
    pre_snippets_time = time.time()
    snippets = [searcher.generate_snippet(id_, query) for id_ in ids]
    # snippets = searcher.generate_snippets(ids, query)
    urls = [searcher.get_url(doc_id) for doc_id in ids]
    snippets_and_urls = zip(snippets, urls)
    # print len(snippets_and_urls)
    end_search_time = time.time()

    # print 'snippets took {}'.format(end_search_time - pre_snippets_time)
    # print 'finding documents took {}'.format(pre_snippets_time - begin_search_time)
    # print 'whole searching procedure took {}'.format(end_search_time - begin_search_time)

    return render(request, 'search_app/results.html',
                  {'query': query, 'snippets_and_urls': snippets_and_urls,
                   'results_count' : len(ids), 'searching_time' : end_search_time - begin_search_time})


@require_http_methods(['GET', 'POST'])
def index_url(request):
    if request.method == 'GET':
        form = IndexUrlForm()
    elif request.method == 'POST':
        form = IndexUrlForm(request.POST, request.FILES)
        if form.is_valid():
            url_to_index = form.cleaned_data['url_to_index']
            filename = form.cleaned_data['file']
            links = []
            if url_to_index:
                links.append(url_to_index)
            elif filename:
                links.extend([x for x in filename.read().split('\n') if x and not x.isspace()])
            # TODO : check it!
            [searcher.indices.add_document(crawl_page(link), link.encode('utf8')) for link in links]
            return HttpResponseRedirect(reverse('search_app:index'))
    return render(request, 'search_app/index_form.html', {'form': form})


@require_http_methods(['GET'])
def indexed_urls(request):
    urls = searcher.indices.id_to_url.values()
    return render(request, 'search_app/urls_list.html', {'urls': urls})

search_app/templates/search_app/base_template.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

search_app/templates/search_app/index.html
{% extends 'search_app/base_template.html' %}
{% block title %}Search page{% endblock %}

{% block content %}
    <div class="container">
    <h1>
        Welcome to anime
    </h1>
        <form method="post" action="{%  url 'search_app:index' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Search!" class="btn ">
        </form>
    </div>
{% endblock %}

search_app/templates/search_app/index_form.html
{% extends 'search_app/base_template.html' %}
{% block title %}Search page{% endblock %}

{% block content %}
    <div class="container">
    <h1>
        Paste address here to index
    </h1>
        <form method="post" action="{%  url 'search_app:index_url' %}"  enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add to index!" class="btn ">
        </form>
    </div>
{% endblock %}

search_app/templates/search_app/results.html
{% extends 'search_app/base_template.html' %}
{% block title %}Search results{% endblock %}

{% block content %}
    <div class="container">
        <h1>
            Requested by user [{{ query }}]
        </h1>
        Found <strong>{{ results_count }}</strong> in <strong>{{ searching_time }}s</strong>


        <ol>
        {% for snippet, url in snippets_and_urls %}
            <div class="container">
                <li><a href="{{ url }}">{{ url }}</a></li>

                ...{% for term, is_in_query in snippet %}
                    {% if is_in_query %}
                        <strong>{{ term }}</strong>
                    {% else %}{{ term }}
                    {% endif %}
                {% endfor %}...

            </div>
        {% endfor %}
        {% if not snippets_and_urls %}
            <p>
                No data found!
            </p>
        {% endif %}

        </ol>

    </div>

{% endblock %}

search_app/templates/search_app/urls_list.html
{% extends 'search_app/base_template.html' %}
{% block title %}Indexed urls{% endblock %}
{% block content %}
    <table class="table table-bordered">
    {% for url in urls %}
    <tr>
        <td><a href="{{ url }}">{{ url }}</a></td>
    </tr>
    {% endfor %}
    </table>

{% endblock %}